# Generated by Django 6.0.7 on 2026-08-03 11:53

import config.encrypted_fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('station', models.CharField(max_length=100)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('sections_of_law', models.CharField(help_text='e.g. PPC 379, 411', max_length=255)),
                ('complainant_name', config.encrypted_fields.EncryptedTextField()),
                ('complainant_contact', config.encrypted_fields.EncryptedTextField(blank=True, default='')),
                ('narrative', models.TextField()),
                ('is_sealed', models.BooleanField(default=False, help_text='Sealed FIRs are excluded from clerk-level queries by row-level security.')),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firs_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under investigation'), ('challan', 'Challan filed'), ('court', 'In court'), ('closed', 'Closed')], default='open', max_length=20)),
                ('court_reference', models.CharField(blank=True, max_length=100)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('fir', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='cases.fir')),
            ],
        ),
    ]
