# Generated by Django 6.0.7 on 2026-08-11 09:05

import config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', config.encrypted_fields.EncryptedTextField()),
                ('last_seen_date', models.DateField()),
                ('last_seen_location', models.CharField(max_length=255)),
                ('reporting_relative_name', config.encrypted_fields.EncryptedTextField()),
                ('reporting_relative_contact', config.encrypted_fields.EncryptedTextField(blank=True, default='')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_persons/')),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('found', 'Found'), ('deceased', 'Deceased')], default='missing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
