# Generated by Django 6.0.7 on 2026-08-07 10:20

import config.encrypted_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', config.encrypted_fields.EncryptedTextField()),
                ('cnic', config.encrypted_fields.EncryptedTextField(blank=True, default='')),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('fingerprint_id', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='criminal_records/')),
                ('status', models.CharField(choices=[('wanted', 'Wanted'), ('in_custody', 'In custody'), ('released', 'Released'), ('deceased', 'Deceased')], default='wanted', max_length=20)),
                ('charges', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('court_name', models.CharField(max_length=150)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_dates', to='records.criminalrecord')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
