# Generated by Django 6.0.7 on 2026-08-12 06:36

import config.encrypted_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('owner_name', config.encrypted_fields.EncryptedTextField()),
                ('owner_contact', config.encrypted_fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('recovered', 'Recovered'), ('wanted', 'Wanted')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
