# Generated by Django 6.0.7 on 2026-08-03 11:53

import django.db.models.deletion
import evidence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=evidence.models.evidence_upload_path)),
                ('sha256_hash', models.CharField(editable=False, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='cases.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChainOfCustodyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('received', 'Received into evidence'), ('transferred', 'Transferred custody'), ('accessed', 'Accessed / reviewed'), ('released', 'Released')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('prev_hash', models.CharField(max_length=64)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_log', to='evidence.evidence')),
            ],
            options={
                'verbose_name_plural': 'Chain of custody entries',
                'ordering': ['timestamp'],
            },
        ),
    ]
