# Generated by Django 6.0.7 on 2026-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('dna', 'DNA'), ('document', 'Document')], default='photo', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='storage_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
